/*
 * Copyright (C) 2022 Lalit Pant <pant.lalit@gmail.com>
 *
 * The contents of this file are subject to the GNU General Public License
 * Version 3 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of
 * the License at http://www.gnu.org/copyleft/gpl.html
 *
 * Software distributed under the License is distributed on an "AS
 * IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * rights and limitations under the License.
 *
 */
package net.kogics.kojo.music
import net.kogics.kojo.music.Duration._

object QuickNote {
  val r_w = Rest(w)
  val r_h = Rest(h)
  val r = Rest(q)
  val r_i = Rest(i)
  val r_s = Rest(s)
  val r_t = Rest(t)

  // generated via quicknote_maker.kojo

  val a3_w = Note(Pitch.A3, w)
  val a3_h = Note(Pitch.A3, h)
  val a3 = Note(Pitch.A3, q)
  val a3_i = Note(Pitch.A3, i)
  val a3_s = Note(Pitch.A3, s)
  val a3_t = Note(Pitch.A3, t)

  val as3_w = Note(Pitch.AS3, w)
  val as3_h = Note(Pitch.AS3, h)
  val as3 = Note(Pitch.AS3, q)
  val as3_i = Note(Pitch.AS3, i)
  val as3_s = Note(Pitch.AS3, s)
  val as3_t = Note(Pitch.AS3, t)

  val bf3_w = Note(Pitch.BF3, w)
  val bf3_h = Note(Pitch.BF3, h)
  val bf3 = Note(Pitch.BF3, q)
  val bf3_i = Note(Pitch.BF3, i)
  val bf3_s = Note(Pitch.BF3, s)
  val bf3_t = Note(Pitch.BF3, t)

  val b3_w = Note(Pitch.B3, w)
  val b3_h = Note(Pitch.B3, h)
  val b3 = Note(Pitch.B3, q)
  val b3_i = Note(Pitch.B3, i)
  val b3_s = Note(Pitch.B3, s)
  val b3_t = Note(Pitch.B3, t)

  val c3_w = Note(Pitch.C3, w)
  val c3_h = Note(Pitch.C3, h)
  val c3 = Note(Pitch.C3, q)
  val c3_i = Note(Pitch.C3, i)
  val c3_s = Note(Pitch.C3, s)
  val c3_t = Note(Pitch.C3, t)

  val cs3_w = Note(Pitch.CS3, w)
  val cs3_h = Note(Pitch.CS3, h)
  val cs3 = Note(Pitch.CS3, q)
  val cs3_i = Note(Pitch.CS3, i)
  val cs3_s = Note(Pitch.CS3, s)
  val cs3_t = Note(Pitch.CS3, t)

  val df3_w = Note(Pitch.DF3, w)
  val df3_h = Note(Pitch.DF3, h)
  val df3 = Note(Pitch.DF3, q)
  val df3_i = Note(Pitch.DF3, i)
  val df3_s = Note(Pitch.DF3, s)
  val df3_t = Note(Pitch.DF3, t)

  val d3_w = Note(Pitch.D3, w)
  val d3_h = Note(Pitch.D3, h)
  val d3 = Note(Pitch.D3, q)
  val d3_i = Note(Pitch.D3, i)
  val d3_s = Note(Pitch.D3, s)
  val d3_t = Note(Pitch.D3, t)

  val ds3_w = Note(Pitch.DS3, w)
  val ds3_h = Note(Pitch.DS3, h)
  val ds3 = Note(Pitch.DS3, q)
  val ds3_i = Note(Pitch.DS3, i)
  val ds3_s = Note(Pitch.DS3, s)
  val ds3_t = Note(Pitch.DS3, t)

  val ef3_w = Note(Pitch.EF3, w)
  val ef3_h = Note(Pitch.EF3, h)
  val ef3 = Note(Pitch.EF3, q)
  val ef3_i = Note(Pitch.EF3, i)
  val ef3_s = Note(Pitch.EF3, s)
  val ef3_t = Note(Pitch.EF3, t)

  val e3_w = Note(Pitch.E3, w)
  val e3_h = Note(Pitch.E3, h)
  val e3 = Note(Pitch.E3, q)
  val e3_i = Note(Pitch.E3, i)
  val e3_s = Note(Pitch.E3, s)
  val e3_t = Note(Pitch.E3, t)

  val f3_w = Note(Pitch.F3, w)
  val f3_h = Note(Pitch.F3, h)
  val f3 = Note(Pitch.F3, q)
  val f3_i = Note(Pitch.F3, i)
  val f3_s = Note(Pitch.F3, s)
  val f3_t = Note(Pitch.F3, t)

  val fs3_w = Note(Pitch.FS3, w)
  val fs3_h = Note(Pitch.FS3, h)
  val fs3 = Note(Pitch.FS3, q)
  val fs3_i = Note(Pitch.FS3, i)
  val fs3_s = Note(Pitch.FS3, s)
  val fs3_t = Note(Pitch.FS3, t)

  val gf3_w = Note(Pitch.GF3, w)
  val gf3_h = Note(Pitch.GF3, h)
  val gf3 = Note(Pitch.GF3, q)
  val gf3_i = Note(Pitch.GF3, i)
  val gf3_s = Note(Pitch.GF3, s)
  val gf3_t = Note(Pitch.GF3, t)

  val g3_w = Note(Pitch.G3, w)
  val g3_h = Note(Pitch.G3, h)
  val g3 = Note(Pitch.G3, q)
  val g3_i = Note(Pitch.G3, i)
  val g3_s = Note(Pitch.G3, s)
  val g3_t = Note(Pitch.G3, t)

  val gs3_w = Note(Pitch.GS3, w)
  val gs3_h = Note(Pitch.GS3, h)
  val gs3 = Note(Pitch.GS3, q)
  val gs3_i = Note(Pitch.GS3, i)
  val gs3_s = Note(Pitch.GS3, s)
  val gs3_t = Note(Pitch.GS3, t)

  val af3_w = Note(Pitch.AF3, w)
  val af3_h = Note(Pitch.AF3, h)
  val af3 = Note(Pitch.AF3, q)
  val af3_i = Note(Pitch.AF3, i)
  val af3_s = Note(Pitch.AF3, s)
  val af3_t = Note(Pitch.AF3, t)

  val a4_w = Note(Pitch.A4, w)
  val a4_h = Note(Pitch.A4, h)
  val a4 = Note(Pitch.A4, q)
  val a4_i = Note(Pitch.A4, i)
  val a4_s = Note(Pitch.A4, s)
  val a4_t = Note(Pitch.A4, t)

  val as4_w = Note(Pitch.AS4, w)
  val as4_h = Note(Pitch.AS4, h)
  val as4 = Note(Pitch.AS4, q)
  val as4_i = Note(Pitch.AS4, i)
  val as4_s = Note(Pitch.AS4, s)
  val as4_t = Note(Pitch.AS4, t)

  val bf4_w = Note(Pitch.BF4, w)
  val bf4_h = Note(Pitch.BF4, h)
  val bf4 = Note(Pitch.BF4, q)
  val bf4_i = Note(Pitch.BF4, i)
  val bf4_s = Note(Pitch.BF4, s)
  val bf4_t = Note(Pitch.BF4, t)

  val b4_w = Note(Pitch.B4, w)
  val b4_h = Note(Pitch.B4, h)
  val b4 = Note(Pitch.B4, q)
  val b4_i = Note(Pitch.B4, i)
  val b4_s = Note(Pitch.B4, s)
  val b4_t = Note(Pitch.B4, t)

  val c4_w = Note(Pitch.C4, w)
  val c4_h = Note(Pitch.C4, h)
  val c4 = Note(Pitch.C4, q)
  val c4_i = Note(Pitch.C4, i)
  val c4_s = Note(Pitch.C4, s)
  val c4_t = Note(Pitch.C4, t)

  val cs4_w = Note(Pitch.CS4, w)
  val cs4_h = Note(Pitch.CS4, h)
  val cs4 = Note(Pitch.CS4, q)
  val cs4_i = Note(Pitch.CS4, i)
  val cs4_s = Note(Pitch.CS4, s)
  val cs4_t = Note(Pitch.CS4, t)

  val df4_w = Note(Pitch.DF4, w)
  val df4_h = Note(Pitch.DF4, h)
  val df4 = Note(Pitch.DF4, q)
  val df4_i = Note(Pitch.DF4, i)
  val df4_s = Note(Pitch.DF4, s)
  val df4_t = Note(Pitch.DF4, t)

  val d4_w = Note(Pitch.D4, w)
  val d4_h = Note(Pitch.D4, h)
  val d4 = Note(Pitch.D4, q)
  val d4_i = Note(Pitch.D4, i)
  val d4_s = Note(Pitch.D4, s)
  val d4_t = Note(Pitch.D4, t)

  val ds4_w = Note(Pitch.DS4, w)
  val ds4_h = Note(Pitch.DS4, h)
  val ds4 = Note(Pitch.DS4, q)
  val ds4_i = Note(Pitch.DS4, i)
  val ds4_s = Note(Pitch.DS4, s)
  val ds4_t = Note(Pitch.DS4, t)

  val ef4_w = Note(Pitch.EF4, w)
  val ef4_h = Note(Pitch.EF4, h)
  val ef4 = Note(Pitch.EF4, q)
  val ef4_i = Note(Pitch.EF4, i)
  val ef4_s = Note(Pitch.EF4, s)
  val ef4_t = Note(Pitch.EF4, t)

  val e4_w = Note(Pitch.E4, w)
  val e4_h = Note(Pitch.E4, h)
  val e4 = Note(Pitch.E4, q)
  val e4_i = Note(Pitch.E4, i)
  val e4_s = Note(Pitch.E4, s)
  val e4_t = Note(Pitch.E4, t)

  val f4_w = Note(Pitch.F4, w)
  val f4_h = Note(Pitch.F4, h)
  val f4 = Note(Pitch.F4, q)
  val f4_i = Note(Pitch.F4, i)
  val f4_s = Note(Pitch.F4, s)
  val f4_t = Note(Pitch.F4, t)

  val fs4_w = Note(Pitch.FS4, w)
  val fs4_h = Note(Pitch.FS4, h)
  val fs4 = Note(Pitch.FS4, q)
  val fs4_i = Note(Pitch.FS4, i)
  val fs4_s = Note(Pitch.FS4, s)
  val fs4_t = Note(Pitch.FS4, t)

  val gf4_w = Note(Pitch.GF4, w)
  val gf4_h = Note(Pitch.GF4, h)
  val gf4 = Note(Pitch.GF4, q)
  val gf4_i = Note(Pitch.GF4, i)
  val gf4_s = Note(Pitch.GF4, s)
  val gf4_t = Note(Pitch.GF4, t)

  val g4_w = Note(Pitch.G4, w)
  val g4_h = Note(Pitch.G4, h)
  val g4 = Note(Pitch.G4, q)
  val g4_i = Note(Pitch.G4, i)
  val g4_s = Note(Pitch.G4, s)
  val g4_t = Note(Pitch.G4, t)

  val gs4_w = Note(Pitch.GS4, w)
  val gs4_h = Note(Pitch.GS4, h)
  val gs4 = Note(Pitch.GS4, q)
  val gs4_i = Note(Pitch.GS4, i)
  val gs4_s = Note(Pitch.GS4, s)
  val gs4_t = Note(Pitch.GS4, t)

  val af4_w = Note(Pitch.AF4, w)
  val af4_h = Note(Pitch.AF4, h)
  val af4 = Note(Pitch.AF4, q)
  val af4_i = Note(Pitch.AF4, i)
  val af4_s = Note(Pitch.AF4, s)
  val af4_t = Note(Pitch.AF4, t)

  val a5_w = Note(Pitch.A5, w)
  val a5_h = Note(Pitch.A5, h)
  val a5 = Note(Pitch.A5, q)
  val a5_i = Note(Pitch.A5, i)
  val a5_s = Note(Pitch.A5, s)
  val a5_t = Note(Pitch.A5, t)

  val as5_w = Note(Pitch.AS5, w)
  val as5_h = Note(Pitch.AS5, h)
  val as5 = Note(Pitch.AS5, q)
  val as5_i = Note(Pitch.AS5, i)
  val as5_s = Note(Pitch.AS5, s)
  val as5_t = Note(Pitch.AS5, t)

  val bf5_w = Note(Pitch.BF5, w)
  val bf5_h = Note(Pitch.BF5, h)
  val bf5 = Note(Pitch.BF5, q)
  val bf5_i = Note(Pitch.BF5, i)
  val bf5_s = Note(Pitch.BF5, s)
  val bf5_t = Note(Pitch.BF5, t)

  val b5_w = Note(Pitch.B5, w)
  val b5_h = Note(Pitch.B5, h)
  val b5 = Note(Pitch.B5, q)
  val b5_i = Note(Pitch.B5, i)
  val b5_s = Note(Pitch.B5, s)
  val b5_t = Note(Pitch.B5, t)

  val c5_w = Note(Pitch.C5, w)
  val c5_h = Note(Pitch.C5, h)
  val c5 = Note(Pitch.C5, q)
  val c5_i = Note(Pitch.C5, i)
  val c5_s = Note(Pitch.C5, s)
  val c5_t = Note(Pitch.C5, t)

  val cs5_w = Note(Pitch.CS5, w)
  val cs5_h = Note(Pitch.CS5, h)
  val cs5 = Note(Pitch.CS5, q)
  val cs5_i = Note(Pitch.CS5, i)
  val cs5_s = Note(Pitch.CS5, s)
  val cs5_t = Note(Pitch.CS5, t)

  val df5_w = Note(Pitch.DF5, w)
  val df5_h = Note(Pitch.DF5, h)
  val df5 = Note(Pitch.DF5, q)
  val df5_i = Note(Pitch.DF5, i)
  val df5_s = Note(Pitch.DF5, s)
  val df5_t = Note(Pitch.DF5, t)

  val d5_w = Note(Pitch.D5, w)
  val d5_h = Note(Pitch.D5, h)
  val d5 = Note(Pitch.D5, q)
  val d5_i = Note(Pitch.D5, i)
  val d5_s = Note(Pitch.D5, s)
  val d5_t = Note(Pitch.D5, t)

  val ds5_w = Note(Pitch.DS5, w)
  val ds5_h = Note(Pitch.DS5, h)
  val ds5 = Note(Pitch.DS5, q)
  val ds5_i = Note(Pitch.DS5, i)
  val ds5_s = Note(Pitch.DS5, s)
  val ds5_t = Note(Pitch.DS5, t)

  val ef5_w = Note(Pitch.EF5, w)
  val ef5_h = Note(Pitch.EF5, h)
  val ef5 = Note(Pitch.EF5, q)
  val ef5_i = Note(Pitch.EF5, i)
  val ef5_s = Note(Pitch.EF5, s)
  val ef5_t = Note(Pitch.EF5, t)

  val e5_w = Note(Pitch.E5, w)
  val e5_h = Note(Pitch.E5, h)
  val e5 = Note(Pitch.E5, q)
  val e5_i = Note(Pitch.E5, i)
  val e5_s = Note(Pitch.E5, s)
  val e5_t = Note(Pitch.E5, t)

  val f5_w = Note(Pitch.F5, w)
  val f5_h = Note(Pitch.F5, h)
  val f5 = Note(Pitch.F5, q)
  val f5_i = Note(Pitch.F5, i)
  val f5_s = Note(Pitch.F5, s)
  val f5_t = Note(Pitch.F5, t)

  val fs5_w = Note(Pitch.FS5, w)
  val fs5_h = Note(Pitch.FS5, h)
  val fs5 = Note(Pitch.FS5, q)
  val fs5_i = Note(Pitch.FS5, i)
  val fs5_s = Note(Pitch.FS5, s)
  val fs5_t = Note(Pitch.FS5, t)

  val gf5_w = Note(Pitch.GF5, w)
  val gf5_h = Note(Pitch.GF5, h)
  val gf5 = Note(Pitch.GF5, q)
  val gf5_i = Note(Pitch.GF5, i)
  val gf5_s = Note(Pitch.GF5, s)
  val gf5_t = Note(Pitch.GF5, t)

  val g5_w = Note(Pitch.G5, w)
  val g5_h = Note(Pitch.G5, h)
  val g5 = Note(Pitch.G5, q)
  val g5_i = Note(Pitch.G5, i)
  val g5_s = Note(Pitch.G5, s)
  val g5_t = Note(Pitch.G5, t)

  val gs5_w = Note(Pitch.GS5, w)
  val gs5_h = Note(Pitch.GS5, h)
  val gs5 = Note(Pitch.GS5, q)
  val gs5_i = Note(Pitch.GS5, i)
  val gs5_s = Note(Pitch.GS5, s)
  val gs5_t = Note(Pitch.GS5, t)

  val af5_w = Note(Pitch.AF5, w)
  val af5_h = Note(Pitch.AF5, h)
  val af5 = Note(Pitch.AF5, q)
  val af5_i = Note(Pitch.AF5, i)
  val af5_s = Note(Pitch.AF5, s)
  val af5_t = Note(Pitch.AF5, t)
}

object QuickSwara {
  // generated via quickswara_maker.kojo

  val sa1_w = Note(SwaraPitch.Sa1, w)
  val sa1_h = Note(SwaraPitch.Sa1, h)
  val sa1 = Note(SwaraPitch.Sa1, q)
  val sa1_i = Note(SwaraPitch.Sa1, i)
  val sa1_s = Note(SwaraPitch.Sa1, s)
  val sa1_t = Note(SwaraPitch.Sa1, t)

  val re_komal1_w = Note(SwaraPitch.Re_komal1, w)
  val re_komal1_h = Note(SwaraPitch.Re_komal1, h)
  val re_komal1 = Note(SwaraPitch.Re_komal1, q)
  val re_komal1_i = Note(SwaraPitch.Re_komal1, i)
  val re_komal1_s = Note(SwaraPitch.Re_komal1, s)
  val re_komal1_t = Note(SwaraPitch.Re_komal1, t)

  val re1_w = Note(SwaraPitch.Re1, w)
  val re1_h = Note(SwaraPitch.Re1, h)
  val re1 = Note(SwaraPitch.Re1, q)
  val re1_i = Note(SwaraPitch.Re1, i)
  val re1_s = Note(SwaraPitch.Re1, s)
  val re1_t = Note(SwaraPitch.Re1, t)

  val ga_komal1_w = Note(SwaraPitch.Ga_komal1, w)
  val ga_komal1_h = Note(SwaraPitch.Ga_komal1, h)
  val ga_komal1 = Note(SwaraPitch.Ga_komal1, q)
  val ga_komal1_i = Note(SwaraPitch.Ga_komal1, i)
  val ga_komal1_s = Note(SwaraPitch.Ga_komal1, s)
  val ga_komal1_t = Note(SwaraPitch.Ga_komal1, t)

  val ga1_w = Note(SwaraPitch.Ga1, w)
  val ga1_h = Note(SwaraPitch.Ga1, h)
  val ga1 = Note(SwaraPitch.Ga1, q)
  val ga1_i = Note(SwaraPitch.Ga1, i)
  val ga1_s = Note(SwaraPitch.Ga1, s)
  val ga1_t = Note(SwaraPitch.Ga1, t)

  val ma1_w = Note(SwaraPitch.Ma1, w)
  val ma1_h = Note(SwaraPitch.Ma1, h)
  val ma1 = Note(SwaraPitch.Ma1, q)
  val ma1_i = Note(SwaraPitch.Ma1, i)
  val ma1_s = Note(SwaraPitch.Ma1, s)
  val ma1_t = Note(SwaraPitch.Ma1, t)

  val ma_tivra1_w = Note(SwaraPitch.Ma_tivra1, w)
  val ma_tivra1_h = Note(SwaraPitch.Ma_tivra1, h)
  val ma_tivra1 = Note(SwaraPitch.Ma_tivra1, q)
  val ma_tivra1_i = Note(SwaraPitch.Ma_tivra1, i)
  val ma_tivra1_s = Note(SwaraPitch.Ma_tivra1, s)
  val ma_tivra1_t = Note(SwaraPitch.Ma_tivra1, t)

  val pa1_w = Note(SwaraPitch.Pa1, w)
  val pa1_h = Note(SwaraPitch.Pa1, h)
  val pa1 = Note(SwaraPitch.Pa1, q)
  val pa1_i = Note(SwaraPitch.Pa1, i)
  val pa1_s = Note(SwaraPitch.Pa1, s)
  val pa1_t = Note(SwaraPitch.Pa1, t)

  val dha_komal1_w = Note(SwaraPitch.Dha_komal1, w)
  val dha_komal1_h = Note(SwaraPitch.Dha_komal1, h)
  val dha_komal1 = Note(SwaraPitch.Dha_komal1, q)
  val dha_komal1_i = Note(SwaraPitch.Dha_komal1, i)
  val dha_komal1_s = Note(SwaraPitch.Dha_komal1, s)
  val dha_komal1_t = Note(SwaraPitch.Dha_komal1, t)

  val dha1_w = Note(SwaraPitch.Dha1, w)
  val dha1_h = Note(SwaraPitch.Dha1, h)
  val dha1 = Note(SwaraPitch.Dha1, q)
  val dha1_i = Note(SwaraPitch.Dha1, i)
  val dha1_s = Note(SwaraPitch.Dha1, s)
  val dha1_t = Note(SwaraPitch.Dha1, t)

  val ni_komal1_w = Note(SwaraPitch.Ni_komal1, w)
  val ni_komal1_h = Note(SwaraPitch.Ni_komal1, h)
  val ni_komal1 = Note(SwaraPitch.Ni_komal1, q)
  val ni_komal1_i = Note(SwaraPitch.Ni_komal1, i)
  val ni_komal1_s = Note(SwaraPitch.Ni_komal1, s)
  val ni_komal1_t = Note(SwaraPitch.Ni_komal1, t)

  val ni1_w = Note(SwaraPitch.Ni1, w)
  val ni1_h = Note(SwaraPitch.Ni1, h)
  val ni1 = Note(SwaraPitch.Ni1, q)
  val ni1_i = Note(SwaraPitch.Ni1, i)
  val ni1_s = Note(SwaraPitch.Ni1, s)
  val ni1_t = Note(SwaraPitch.Ni1, t)

  val sa_w = Note(SwaraPitch.Sa, w)
  val sa_h = Note(SwaraPitch.Sa, h)
  val sa = Note(SwaraPitch.Sa, q)
  val sa_i = Note(SwaraPitch.Sa, i)
  val sa_s = Note(SwaraPitch.Sa, s)
  val sa_t = Note(SwaraPitch.Sa, t)

  val re_komal_w = Note(SwaraPitch.Re_komal, w)
  val re_komal_h = Note(SwaraPitch.Re_komal, h)
  val re_komal = Note(SwaraPitch.Re_komal, q)
  val re_komal_i = Note(SwaraPitch.Re_komal, i)
  val re_komal_s = Note(SwaraPitch.Re_komal, s)
  val re_komal_t = Note(SwaraPitch.Re_komal, t)

  val re_w = Note(SwaraPitch.Re, w)
  val re_h = Note(SwaraPitch.Re, h)
  val re = Note(SwaraPitch.Re, q)
  val re_i = Note(SwaraPitch.Re, i)
  val re_s = Note(SwaraPitch.Re, s)
  val re_t = Note(SwaraPitch.Re, t)

  val ga_komal_w = Note(SwaraPitch.Ga_komal, w)
  val ga_komal_h = Note(SwaraPitch.Ga_komal, h)
  val ga_komal = Note(SwaraPitch.Ga_komal, q)
  val ga_komal_i = Note(SwaraPitch.Ga_komal, i)
  val ga_komal_s = Note(SwaraPitch.Ga_komal, s)
  val ga_komal_t = Note(SwaraPitch.Ga_komal, t)

  val ga_w = Note(SwaraPitch.Ga, w)
  val ga_h = Note(SwaraPitch.Ga, h)
  val ga = Note(SwaraPitch.Ga, q)
  val ga_i = Note(SwaraPitch.Ga, i)
  val ga_s = Note(SwaraPitch.Ga, s)
  val ga_t = Note(SwaraPitch.Ga, t)

  val ma_w = Note(SwaraPitch.Ma, w)
  val ma_h = Note(SwaraPitch.Ma, h)
  val ma = Note(SwaraPitch.Ma, q)
  val ma_i = Note(SwaraPitch.Ma, i)
  val ma_s = Note(SwaraPitch.Ma, s)
  val ma_t = Note(SwaraPitch.Ma, t)

  val ma_tivra_w = Note(SwaraPitch.Ma_tivra, w)
  val ma_tivra_h = Note(SwaraPitch.Ma_tivra, h)
  val ma_tivra = Note(SwaraPitch.Ma_tivra, q)
  val ma_tivra_i = Note(SwaraPitch.Ma_tivra, i)
  val ma_tivra_s = Note(SwaraPitch.Ma_tivra, s)
  val ma_tivra_t = Note(SwaraPitch.Ma_tivra, t)

  val pa_w = Note(SwaraPitch.Pa, w)
  val pa_h = Note(SwaraPitch.Pa, h)
  val pa = Note(SwaraPitch.Pa, q)
  val pa_i = Note(SwaraPitch.Pa, i)
  val pa_s = Note(SwaraPitch.Pa, s)
  val pa_t = Note(SwaraPitch.Pa, t)

  val dha_komal_w = Note(SwaraPitch.Dha_komal, w)
  val dha_komal_h = Note(SwaraPitch.Dha_komal, h)
  val dha_komal = Note(SwaraPitch.Dha_komal, q)
  val dha_komal_i = Note(SwaraPitch.Dha_komal, i)
  val dha_komal_s = Note(SwaraPitch.Dha_komal, s)
  val dha_komal_t = Note(SwaraPitch.Dha_komal, t)

  val dha_w = Note(SwaraPitch.Dha, w)
  val dha_h = Note(SwaraPitch.Dha, h)
  val dha = Note(SwaraPitch.Dha, q)
  val dha_i = Note(SwaraPitch.Dha, i)
  val dha_s = Note(SwaraPitch.Dha, s)
  val dha_t = Note(SwaraPitch.Dha, t)

  val ni_komal_w = Note(SwaraPitch.Ni_komal, w)
  val ni_komal_h = Note(SwaraPitch.Ni_komal, h)
  val ni_komal = Note(SwaraPitch.Ni_komal, q)
  val ni_komal_i = Note(SwaraPitch.Ni_komal, i)
  val ni_komal_s = Note(SwaraPitch.Ni_komal, s)
  val ni_komal_t = Note(SwaraPitch.Ni_komal, t)

  val ni_w = Note(SwaraPitch.Ni, w)
  val ni_h = Note(SwaraPitch.Ni, h)
  val ni = Note(SwaraPitch.Ni, q)
  val ni_i = Note(SwaraPitch.Ni, i)
  val ni_s = Note(SwaraPitch.Ni, s)
  val ni_t = Note(SwaraPitch.Ni, t)

  val sa3_w = Note(SwaraPitch.Sa3, w)
  val sa3_h = Note(SwaraPitch.Sa3, h)
  val sa3 = Note(SwaraPitch.Sa3, q)
  val sa3_i = Note(SwaraPitch.Sa3, i)
  val sa3_s = Note(SwaraPitch.Sa3, s)
  val sa3_t = Note(SwaraPitch.Sa3, t)

  val re_komal3_w = Note(SwaraPitch.Re_komal3, w)
  val re_komal3_h = Note(SwaraPitch.Re_komal3, h)
  val re_komal3 = Note(SwaraPitch.Re_komal3, q)
  val re_komal3_i = Note(SwaraPitch.Re_komal3, i)
  val re_komal3_s = Note(SwaraPitch.Re_komal3, s)
  val re_komal3_t = Note(SwaraPitch.Re_komal3, t)

  val re3_w = Note(SwaraPitch.Re3, w)
  val re3_h = Note(SwaraPitch.Re3, h)
  val re3 = Note(SwaraPitch.Re3, q)
  val re3_i = Note(SwaraPitch.Re3, i)
  val re3_s = Note(SwaraPitch.Re3, s)
  val re3_t = Note(SwaraPitch.Re3, t)

  val ga_komal3_w = Note(SwaraPitch.Ga_komal3, w)
  val ga_komal3_h = Note(SwaraPitch.Ga_komal3, h)
  val ga_komal3 = Note(SwaraPitch.Ga_komal3, q)
  val ga_komal3_i = Note(SwaraPitch.Ga_komal3, i)
  val ga_komal3_s = Note(SwaraPitch.Ga_komal3, s)
  val ga_komal3_t = Note(SwaraPitch.Ga_komal3, t)

  val ga3_w = Note(SwaraPitch.Ga3, w)
  val ga3_h = Note(SwaraPitch.Ga3, h)
  val ga3 = Note(SwaraPitch.Ga3, q)
  val ga3_i = Note(SwaraPitch.Ga3, i)
  val ga3_s = Note(SwaraPitch.Ga3, s)
  val ga3_t = Note(SwaraPitch.Ga3, t)

  val ma3_w = Note(SwaraPitch.Ma3, w)
  val ma3_h = Note(SwaraPitch.Ma3, h)
  val ma3 = Note(SwaraPitch.Ma3, q)
  val ma3_i = Note(SwaraPitch.Ma3, i)
  val ma3_s = Note(SwaraPitch.Ma3, s)
  val ma3_t = Note(SwaraPitch.Ma3, t)

  val ma_tivra3_w = Note(SwaraPitch.Ma_tivra3, w)
  val ma_tivra3_h = Note(SwaraPitch.Ma_tivra3, h)
  val ma_tivra3 = Note(SwaraPitch.Ma_tivra3, q)
  val ma_tivra3_i = Note(SwaraPitch.Ma_tivra3, i)
  val ma_tivra3_s = Note(SwaraPitch.Ma_tivra3, s)
  val ma_tivra3_t = Note(SwaraPitch.Ma_tivra3, t)

  val pa3_w = Note(SwaraPitch.Pa3, w)
  val pa3_h = Note(SwaraPitch.Pa3, h)
  val pa3 = Note(SwaraPitch.Pa3, q)
  val pa3_i = Note(SwaraPitch.Pa3, i)
  val pa3_s = Note(SwaraPitch.Pa3, s)
  val pa3_t = Note(SwaraPitch.Pa3, t)

  val dha_komal3_w = Note(SwaraPitch.Dha_komal3, w)
  val dha_komal3_h = Note(SwaraPitch.Dha_komal3, h)
  val dha_komal3 = Note(SwaraPitch.Dha_komal3, q)
  val dha_komal3_i = Note(SwaraPitch.Dha_komal3, i)
  val dha_komal3_s = Note(SwaraPitch.Dha_komal3, s)
  val dha_komal3_t = Note(SwaraPitch.Dha_komal3, t)

  val dha3_w = Note(SwaraPitch.Dha3, w)
  val dha3_h = Note(SwaraPitch.Dha3, h)
  val dha3 = Note(SwaraPitch.Dha3, q)
  val dha3_i = Note(SwaraPitch.Dha3, i)
  val dha3_s = Note(SwaraPitch.Dha3, s)
  val dha3_t = Note(SwaraPitch.Dha3, t)

  val ni_komal3_w = Note(SwaraPitch.Ni_komal3, w)
  val ni_komal3_h = Note(SwaraPitch.Ni_komal3, h)
  val ni_komal3 = Note(SwaraPitch.Ni_komal3, q)
  val ni_komal3_i = Note(SwaraPitch.Ni_komal3, i)
  val ni_komal3_s = Note(SwaraPitch.Ni_komal3, s)
  val ni_komal3_t = Note(SwaraPitch.Ni_komal3, t)

  val ni3_w = Note(SwaraPitch.Ni3, w)
  val ni3_h = Note(SwaraPitch.Ni3, h)
  val ni3 = Note(SwaraPitch.Ni3, q)
  val ni3_i = Note(SwaraPitch.Ni3, i)
  val ni3_s = Note(SwaraPitch.Ni3, s)
  val ni3_t = Note(SwaraPitch.Ni3, t)
}

object QuickBeat {
  val pbd_w = Beat(Drum.ACOUSTIC_BASS_DRUM, w)
  val pbd_h = Beat(Drum.ACOUSTIC_BASS_DRUM, h)
  val pbd = Beat(Drum.ACOUSTIC_BASS_DRUM, q)
  val pbd_i = Beat(Drum.ACOUSTIC_BASS_DRUM, i)

  val phc_w = Beat(Drum.HAND_CLAP, w)
  val phc_h = Beat(Drum.HAND_CLAP, h)
  val phc = Beat(Drum.HAND_CLAP, q)
  val phc_i = Beat(Drum.HAND_CLAP, i)
}
